site_name: CDP

markdown_extensions:
  - meta

theme:
  name: material
  logo: img/logo.png
  features:
    - navigation.top
    - navigation.instant
    - navigation.tracking
    - navigation.indexes
    - navigation.tabs
  hide:
    - toc

extra_css:
  - css/extra_css.css