site_name: CDP

theme:
  name: material
  logo: img/logo.png
  language: pt-BR
  features:
    - navigation.top
    - navigation.instant
    - navigation.tracking
    - navigation.indexes
    - navigation.tabs
  palette:
    - scheme: cia-hering
      toggle:
        icon: material/toggle-switch-off-outline
        name: Modo Escuro
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Modo Claro

extra_css:
  - css/extra_css.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/douglasdmarques/mkdocs
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/cia-hering
    - icon: fontawesome/solid/paper-plane
      link: mailto:douglas.marques@ciahering.com.br

plugins:
  - search
  - charts

extra_javascript:
  - https://cdn.jsdelivr.net/npm/vega@5
  - https://cdn.jsdelivr.net/npm/vega-lite@5
  - https://cdn.jsdelivr.net/npm/vega-embed@6

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: vegalite
          class: vegalite
          format: !!python/name:mkdocs_charts_plugin.fences.fence_vegalite
  - meta
  - attr_list